Dashboard/dashboa/appdash/urls.py
from os import name

from django.urls import path
from .views.estudiante.views import *
from .views.institucion.views import *
from .views.municipio.views import *
from .views.prueba.views import *
from .views.tiempo.views import *
from .views.resultado.views import *
from .views.NumEstuPorMunicipio.views import *
from .views.dashboard.views import *
from .views.graficaest.views import *
from .views.puntaje_ciencias_naturales.views import *
from .views.puntaje_lenguaje.views import *
from .views.puntaje_matematicas.views import *
from .views.puntaje_compencias.views import  *
from .views.NumEstuPorInstituion.views import *
from .views.inicio.views import *
from .views.Boxplot.views import *
from .views.Biplot.views import *
from .views.contacto.views import *
from .views.home.views import *
from .views.BD.views import *
from .views.dashboard2.views import *
from .views.dashboardGeneral.views import *

#from .views.grafica_est.views import *

app_name = 'appdash'

urlpatterns = [
    path('estudiante/list/', EstudianteListView.as_view(), name='estudiante_list'),
    path('institucion/list/', InstitucionesListView.as_view(), name='institucion_list'),
    path('municipio/list/', MunicipiosListView.as_view(), name='municipio_list'),
    path('prueba/list/', PruebasListView.as_view(), name='prueba_list'),
    path('tiempo/list/', TiempoListView.as_view(), name='tiempo_list'),
    path('resultado/list/', ResultadosListView.as_view(), name='resultado_list'),
    path('NumEstuPorMunicipio/list/', NumEstuPorMunicipioListView, name='NumEstuPorMunicipio_list'),
    path('dashboard/', DashboardView.as_view(), name='dashboard_list'),
    path('graficaest/list', grafichtml, name='graficaest_list'),
    path('grafica_est/', grafica, name='grafica_est'),
    #path('NumEstuPorTipoEsta/', Num_Estu_Por_MunicipioHtml, name='NumEstuPorTipoEsta'),
    path('NEstuPorMunicipio/list', Num_Estu_Por_Municipio, name='Num_Estu_Por_Municipio'),
    path('home/', HomeListView, name='home_list'),
    path('home/list/', HomeHtml, name='home_list1'),
    path('bd/list/', BdListView, name='BD_list'),
    path('tabla_puntaje_nat/list', tabla_puntaje_nat, name='tabla_puntaje_nat_list'),
    path('grafica_puntaje_nat/', grafica_puntaje_nat, name='grafica_puntaje_nat'),
    path('tabla_puntaje_leng/list', tabla_puntaje_leng, name='tabla_puntaje_leng_list'),
    path('grafica_puntaje_leng/', grafica_puntaje_leng, name='grafica_puntaje_leng'),
    path('tabla_puntaje_mat/list', tabla_puntaje_mat, name='tabla_puntaje_mat_list'),
    path('grafica_puntaje_mat', grafica_puntaje_mat, name='grafica_puntaje_mat'),
    path('tabla_puntaje_comp/list', tabla_puntaje_comp, name='tabla_puntaje_comp_list'),
    path('grafica_puntaje_comp', grafica_puntaje_comp, name='grafica_puntaje_comp'),
    path('NumEstuPorInstitucionListView/list', NumEstuPorInstitucionListView, name='NumEstuPorInstitucionListView_list'),
    path('Num_Estu_Por_Institucion', Num_Estu_Por_Institucion, name='Num_Estu_Por_Institucion'),
    path('inicio/list', tabla_inicio, name='inicio_list'),
    path('inicio', grafica_inicio, name='inicio'),
    path('contacto/list', contacto, name='contacto_list'),
    path('dashboard2/', DashboardListView, name='dashboard_list'),
    path('dashboard2/list/', DashboardHtml, name='dashboard_list1'),
    path('dashboard2_ge/', DashboardListViewGeneral, name='dashboard_listG'),
    path('dashboard2_ge/list/', DashboardHtmlGeneral, name='dashboard_list1G'),
    path('boxplot/list', tabla_boxplot, name='boxplot_list'),
    path('boxplot', grafica_boxplot, name='boxplot'),
    path('biplot/list', tabla_biplot, name='biplot_list'),
    path('biplot', grafica_biplot, name='biplot'),
    #path('graficaesthi/list', grafichtmlhi, name='graficaest_listhi'),
    #path('grafica_esthi/', graficahi, name='grafica_esthi'),
    #path('estudiante/list2/', estudiante_list, name='estudiante_list2'),
]

Dashboard/dashboa/dashboa/urls.py
from django.contrib import admin
from django.urls import path, include
from login.views import *

#from appdash.views import myfirstview

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),
    path('appdash/', include('appdash.urls'))
]

Dashboard/dashboa/login/urls.py
from django.urls import path

from login.views import LoginFormView, LogoutRedirectView

urlpatterns = [
    path('', LoginFormView.as_view(), name='login'),
    #path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('logout/', LogoutRedirectView.as_view(), name='logout')
]

Dashboard/dashboa/appdash/views/dashboard/views.py
from django.db.models import Sum
from django.db.models.functions import Coalesce
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from django.urls import reverse_lazy
from datetime import datetime
from django.shortcuts import render

#from core.erp.models import Sale


class DashboardView(TemplateView):
    template_name = 'grahichart/list.html'


    '''def get_graph_result_mun_lenguaje(self):
            try:
                from django.db import connection
                with connection.cursor() as cursor:
                    cursor.execute(
                        "SELECT muni_nombre, ins_tipo_estab, SUM(numero_estu) FROM dim_municipios JOIN fact_saber5 USING(muni_id_ente) JOIN dim_instituciones USING(id_institucion) GROUP BY 1,2 ORDER BY 1,2")
                    rawData = cursor.fetchall()
                    result = []
                    for r in rawData:
                        result.append(list(r))
                    data = []
                    for m in range(1, 14):
                        contexto=result.objects.filter(muni_nombre=m).aggregate(r=Coalesce(Sum('PROMEDIO'),0).get('r'))
                        data.append(contexto)
            except:
                    pass
            return data
        
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['title'] = 'Consulta'
            context['entity'] = 'Consulta'
            context['list_url'] = reverse_lazy('appdash:dashboard_list')
            context['panel'] = 'Panel de administrador'
            #context['graph_result_mun_lenguaje'] = self.get_graph_result_mun_lenguaje()
            return context'''

Dashboard/dashboa/appdash/views/home/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from appdash.models import DimEstudiante, DimInstituciones, DimMunicipios, FactSaber5, DimPrueba, DimTiempo
from appdash.forms import EstudianteForm
from django.db.models import Count, Avg, Sum, Func

class Round(Func):
 function = 'ROUND'
 template='%(function)s(%(expressions)s, 2)'

def HomeListView(request):

    label = []
    dato = []

    puntaje = request.GET['puntaje']
    municipio = request.GET['municipio']
    inst = request.GET['inst']
    anios = request.GET['anios']

    if (anios == "TODOS"):
        if (municipio == "TODOS"):
            results = FactSaber5.objects.values('muni_id_ente__muni_nombre', 'anio').annotate(prom=Round(Avg(puntaje))).order_by('muni_id_ente__muni_nombre', 'anio')
            for entry in results:
                label.append(entry['muni_id_ente__muni_nombre'] + " : " + entry['anio'])  # guarda nombre del departamento ya agrupado
                dato.append(entry['prom'])  # guarda promedio de cada grupo creado(por municipio)
        else:
            if (inst == "General"):
                results = FactSaber5.objects.values('id_institucion__ins_nombre', 'anio').annotate(
                    prom=Round(Avg(puntaje))).filter(muni_id_ente__muni_nombre=municipio).order_by(
                    'id_institucion__ins_nombre', 'anio')
                for entry in results:
                    label.append(entry['id_institucion__ins_nombre'] + " : " + entry[
                        'anio'])  # guarda nombre del departamento ya agrupado
                    dato.append(entry['prom'])  # guarda promedio de cada grupo creado(por municipio)
            else:
                results = FactSaber5.objects.values('id_institucion__ins_nombre', 'anio').annotate(
                    prom=Round(Avg(puntaje))).filter(muni_id_ente__muni_nombre=municipio,id_institucion__ins_nombre=inst).order_by(
                    'id_institucion__ins_nombre', 'anio')
                for entry in results:
                    label.append(entry['id_institucion__ins_nombre'] + " : " + entry[
                        'anio'])  # guarda nombre del departamento ya agrupado
                    dato.append(entry['prom'])  # guarda promedio de cada grupo creado(por municipio)
    else:
        if (municipio == "TODOS"):
            results = FactSaber5.objects.values('muni_id_ente__muni_nombre', 'anio').annotate(
                prom=Round(Avg(puntaje))).filter(anio=anios).order_by('muni_id_ente__muni_nombre', 'anio')
            for entry in results:
                label.append(entry['muni_id_ente__muni_nombre'] + " : " + entry[
                    'anio'])  # guarda nombre del departamento ya agrupado
                dato.append(entry['prom'])  # guarda promedio de cada grupo creado(por municipio)
        else:
            if (inst == "General"):
                results = FactSaber5.objects.values('id_institucion__ins_nombre', 'anio').annotate(
                    prom=Round(Avg(puntaje))).filter(muni_id_ente__muni_nombre=municipio, anio=anios).order_by(
                    'id_institucion__ins_nombre', 'anio')
                for entry in results:
                    label.append(entry['id_institucion__ins_nombre'] + " : " + entry[
                        'anio'])  # guarda nombre del departamento ya agrupado
                    dato.append(entry['prom'])  # guarda promedio de cada grupo creado(por municipio)
            else:
                results = FactSaber5.objects.values('id_institucion__ins_nombre', 'anio').annotate(
                    prom=Round(Avg(puntaje))).filter(muni_id_ente__muni_nombre=municipio,
                                                     id_institucion__ins_nombre=inst, anio=anios).order_by(
                    'id_institucion__ins_nombre', 'anio')
                for entry in results:
                    label.append(entry['id_institucion__ins_nombre'] + " : " + entry[
                        'anio'])  # guarda nombre del departamento ya agrupado
                    dato.append(entry['prom'])  # guarda promedio de cada grupo creado(por municipio)


    return JsonResponse(data={

        'labels': label,
        'data': dato,
    })

def HomeHtml(request):
    title = "Consulta Dashboard >> Puntajes"
    list_url = reverse_lazy('appdash:home_list1')
    entity = 'Consulta'

    contexto = {"title": title, "list_url": list_url, "entity": entity}

    return render(request, "home/list.html", contexto)

Dashboard/dashboa/templates/body.html
{% extends "home.html" %}
{% block body %}
    <body class="hold-transition sidebar-collapse layout-top-nav">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        {% include 'menu.html' %}
        <!--  Content  -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> <small>PRUEBAS SABER 5 EX-PROVINCIA DE OBANDO</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'appdash:inicio_list' %}">Inicio</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>  <!--entity variable con el nombre de la tabla en que se encuentra esta configurada en cada una de las  vistas views.py-->
                                <!-- list_url esta configurado en views.py -->
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container">
                {% block content %}

                {% endblock %}
                </div>
            </div>
        </div>
    <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-6">
        <h6 align="center">
                Equipo de Desarrollo
        </h6>
        <br>
        <p align="center">
            Dario Ceballos Rosero <br>  3178102840 <br>  daridr8761@gmail.com
        </p>
        <p align="center">
            Alexander Santander Arias <br> 3182952346 <br> dasa.deidara@hotmail.com
        </p>
        <div class="card-header">
        </div>

        <br>
        <h6 align="center">
            Director de Trabajo de Grado
        </h6>

        <p align="center">
            Phd. Ricardo Timaran Pereira <br> siritimar@gmail.com
        </p>
    </div>
    </aside>
    {% include 'footer.html' %}
    </div>
    <!-- Block JavaScript -->
    {% block javascript %}

    {% endblock %}
    </body>
{% endblock %}

Dashboard/dashboa/templates/dashboard.html
<!--{% extends 'list.html' %}
{% load static %}
{% block head %}
    <script src="{% static 'lib/highcharts-8.1.2/highcharts.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/exporting.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/export-data.js' %}"></script>
    <script src="{% static 'lib/highcharts-8.1.2/modules/accessibility.js' %}"></script>
{% endblock %}

{% block content%}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <div id="container"></div>
            </div>
        </div>
    </div>

    <script type="application/javascript">
       Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'Monthly Average Rainfall'
    },
    subtitle: {
        text: 'Source: WorldClimate.com'
    },
    xAxis: {
        categories: [
            'Aldana',
            'Contadero',
            'Cordoba',
            'Cuaspud',
            'Cumbal',
            'Funes',
            'Guachucal',
            'Gualmatan',
            'Iles',
            'Ipiales',
            'Potosi',
            'Puerres',
            'Pupiales'
        ],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'Rainfall (mm)'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [{
        name: 'Tokyo',
        data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4, 60.0]

    }]
});

    </script>

{% endblock %} -->

<!--    function get_graph_result_mun_lenguaje(){

        $.ajax:({
                url: window.location.pathname,
                type: 'POST',
                data: {
                    'action': 'get_graph_result_mun_lenguaje'
                },
                dataType: 'json',
            }).done(function(data) {
                    if(!data.hasOwnProperty('error')){
                        console.log(data);
                        return false;
                    }
                    message.error(data.error);
            }).fail(function(jqXHR, textStatus, errorThrown) {
                    alert(textStatus + ': ' + errorThrown);
            }).always(function(data){

         });
    }

    $(function() {
            get_graph_result_mun_lenguaje();
    });
-->

Dashboard/dashboa/templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}

<form method="post" action=".">
    <!--action es hacia donde se va a ir como se trabaja dentro de la misma url solo se le pone un punto-->
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-trash"></i> <!-- fa-trash icono parte superior izquierda un bote de basura-->
                {{ title }}
            </h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-ban"></i> ha ocurrido un error al querer guardar un registro</h5>
                <ul>
                    {% for field in form %}
                    {% for error in field.errors %}
                    <li>{{error}}</li>
                    {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}
            <div class="alert alert-danger alert-dismissible">
                  <h5><i class="icon fas fa-ban"></i>  Notificacion!</h5>
                  Estas seguro de eliminar el registro Numero {{object.id_estudiante}}?
            </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type='submit' class="btn btn-primary btn-flat">
                <i class="fas fa-save"></i> Si, Aceptar
            </button>
            <a href="{{ list_url }}" class="btn btn-info btn-flat">
                <i class="fas fa-times"></i> Cancelar
            </a>
        </div>
    </div>
</form>

<script>
    $('form').on('submit', function(e){
        e.preventDefault();
        var parameters = $(this).serializeArray();
        $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: {},
                dataType: 'json'
        }).done(function(data) {
                console.log(data);
                if(!data.hasOwnProperty('error')){
                        location.href = '{{ list_url }}';
                        return false;
                }
                        message_error(data.error);
                }).fail(function(jqXHR, textStatus, errorThrown) {
                            alert(textStatus+': '+errorThrown);
                }).always(function(data) {

         });
    });
</script>
{% endblock %}

Dashboard/dashboa/templates/footer.html
<!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Ingenieria de Sistemas
    </div>
    <!-- Default to the left -->
    <strong>Link <a href="https://www.udenar.edu.co/ipiales/">Universidad de Nariño</a>.</strong> Ipiales.
  </footer>

Dashboard/dashboa/templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}

{% block content %}

<form method="post" action=".">
    <!--action es hacia donde se va a ir como se trabaja dentro de la misma url solo se le pone un punto-->
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                {% if action == 'add' %}
                    <i class="fas fa-plus"></i>  <!--icono de agregar nuevo registro en la parte izquierda del formulario de editar create.html-->
                {% else %}
                    <i class="fas fa-edit"></i>  <!--icono de editar en la parte izquierda del formulario de editar -->
                {% endif %}

                {{ title }}
            </h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{ action }}">
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <h5><i class="icon fas fa-ban"></i> ha ocurrido un error al querer guardar un registro</h5>
                <ul>
                    {% for field in form %}
                    {% for error in field.errors %}
                    <li>{{error}}</li>
                    {% endfor %}
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="Id">{{ field.label }}:</label>
                {{field|add_class:'form-control'|attr:'autocomplete:off'}}
            </div>
            {% endfor %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type='submit' class="btn btn-primary btn-flat">
                <i class="fas fa-save"></i> Guardar Registro
            </button>
        </div>
    </div>
</form>
<script>
    {% if form.errors %}
    var errors = '';
                    {% for field in form %}
                    {% for error in field.errors %}
                                 errors+='{{ error }}\n ';
                    {% endfor %}
                    {% endfor %}
                    Swal.fire({
                        title: 'Error!',
                        text: 'errors',
                        icon: 'error'
                    });
    {% endif %}

    $('form').on('submit', function(e){
        e.preventDefault();
        var parameters = $(this).serializeArray();
        $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                dataType: 'json'
        }).done(function(data) {
                console.log(data);
                if(!data.hasOwnProperty('error')){
                        location.href = '{{ list_url }}';
                        return false;
                }
                        message_error(data.error);
                }).fail(function(jqXHR, textStatus, errorThrown) {
                            alert(textStatus+': '+errorThrown);
                }).always(function(data) {

         });
    });

    alert_jqueryconfirm();


</script>
{% endblock %}

Dashboard/dashboa/templates/menu.html
{% load static %}
<!-- Main Sidebar Container -->   <!--  ************* Menu lado Izquierdo Contraible ****************** -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'lib/adminlte-3.0.5/img/Logo3.png' %}"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Saber Expo BI 5 </span>
</a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{% static 'lib/adminlte-3.0.5/img/user.png' %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Bienvenid@ <br> {{ request.user.username }}</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'appdash:home_list1' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Consultar Puntajes</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:dashboard_list1' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Consultar Numero de Estudiantes</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:dashboard_list1G' %}" class="nav-link">
                <!--<a href="#" class="nav-link">-->
                  <i class="far fa-circle nav-icon"></i>
                  <p>Dashboard General</p>
                </a>
              </li>
            </ul>
          </li>
          <!--<li class="nav-item">
            <a href="../widgets.html" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Widgets
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>-->
          {% if request.user.is_authenticated %}  <!-- si esta autenticado como admin puede ingrear el nuevo año -->
                <li class="nav-item has-treeview">
                  <a href="#" class="nav-link deactive">
                    <i class="nav-icon fas fa-copy"></i>
                    <p>
                      Carga Nuevo Año
                      <i class="fas fa-angle-left right"></i>
                      <span class="badge badge-info right">BD</span>
                    </p>
                  </a>
                  <ul class="nav nav-treeview">
                    <li class="nav-item">
                      <a href="{% url 'appdash:BD_list' %}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Cargar Archivo</p>
                      </a>
                    </li>
                  </ul>
                </li>
          {% endif %}
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-chart-pie"></i>
              <p>
                Cubos
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'appdash:NumEstuPorMunicipio_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Numero de Estudiantes por Municipio y Años Global</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:graficaest_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Numero de Estudiantes por Municipio General</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:tabla_puntaje_nat_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Puntaje Area Ciencias Naturales por Municipio y Año General</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:tabla_puntaje_leng_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Puntaje Area Lenguaje por Municipio y Año General</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:tabla_puntaje_mat_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Puntaje Matematicas por Municipio y Año General</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:tabla_puntaje_comp_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Puntaje Competencias por Municipio y Año General</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'appdash:NumEstuPorInstitucionListView_list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Consultar Numero de Estudiantes por Años Global</p>
                </a>
              </li>
            </ul>
          </li>
          <!--  Graficos Estadisticos Boxplot y Biplot -->
          <li class="nav-item has-treeview">
                  <a href="#" class="nav-link deactive">
                    <i class="nav-icon fas fa-chart-area"></i>
                    <p>
                          Estadistica
                      <i class="fas fa-angle-left right"></i>
                    </p>
                  </a>
                  <ul class="nav nav-treeview">
                    <li class="nav-item">
                      <a href="{% url 'appdash:boxplot_list' %}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Boxplot</p>
                      </a>
                    </li>
                    <li class="nav-item">
                      <a href="{% url 'appdash:biplot_list' %}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Biplot</p>
                      </a>
                    </li>
                  </ul>
                </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>